/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquatRouteImport } from './routes/squat'
import { Route as PressRouteImport } from './routes/press'
import { Route as DeadliftRouteImport } from './routes/deadlift'

const SquatRoute = SquatRouteImport.update({
  id: '/squat',
  path: '/squat',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadliftRoute = DeadliftRouteImport.update({
  id: '/deadlift',
  path: '/deadlift',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/deadlift': typeof DeadliftRoute
  '/press': typeof PressRoute
  '/squat': typeof SquatRoute
}
export interface FileRoutesByTo {
  '/deadlift': typeof DeadliftRoute
  '/press': typeof PressRoute
  '/squat': typeof SquatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/deadlift': typeof DeadliftRoute
  '/press': typeof PressRoute
  '/squat': typeof SquatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/deadlift' | '/press' | '/squat'
  fileRoutesByTo: FileRoutesByTo
  to: '/deadlift' | '/press' | '/squat'
  id: '__root__' | '/deadlift' | '/press' | '/squat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeadliftRoute: typeof DeadliftRoute
  PressRoute: typeof PressRoute
  SquatRoute: typeof SquatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squat': {
      id: '/squat'
      path: '/squat'
      fullPath: '/squat'
      preLoaderRoute: typeof SquatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlift': {
      id: '/deadlift'
      path: '/deadlift'
      fullPath: '/deadlift'
      preLoaderRoute: typeof DeadliftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DeadliftRoute: DeadliftRoute,
  PressRoute: PressRoute,
  SquatRoute: SquatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
